### ISSUE TITLE
How do I use pydeequ with my pyspark project?

### ISSUE THREAD

**Issue by mundra-aman** [margitaii/pydeequ#1]

**Comment by margitaii** [comment]
Hi, how does your project look like? Do you run spark scripts with spark-submit or pyspark or python REPL?
There are couple of example files in the src/pydeequ/examples folder in the repo. I can help you better if you give ma a bit more detail about your project.

**Comment by mundra-aman** [comment]
Hi, I'm using pyspark scripts for my ETL and trigger them via spark-submit.
I want to use pydeeque to run a few verification constraints on my dataset.

Also I want to contribute to your project. How and from where do I start?

**Comment by margitaii** [comment]
Hi, sorry for my late reply. So with spark-submit you need to give the deequ jar file as parameter when you execute your pydeequ .py, like
`$ spark-submit --jars ~/mywork/deequ-1.0.3-rc2.jar myfile.py`

As for the VerificationSuite: you can find an example of the currently implemented deequ checks in the [basic_usage.py](https://github.com/margitaii/pydeequ/blob/master/src/pydeequ/examples/basic_usage.py). Hope it helps! If you have some special DQ check you want to execute submit an issue and I'll have a look. The assertion parameters are implemented as lambda functions on the python side.

Great to hear that you want to contribute :). I created a couple is issues what I am facing now, pick any of them, you might have an idea how to solve them. There are certain Scala classes what I do not now how to wrap on the python side.
For contributions let's follow the standard fork & pull request workflow.

**Comment by Mika24** [comment]
Hi, I would like to use pydeequ in the databricks, where I run the notebook with pyspark. Since there is no release currently, any suggestion I can properly package it and upload to the databricks cluster?

**Comment by hafizmujadid** [comment]
I want to use it in emr notebook. I don't know how can it be run with emr. Can someone help?

**Comment by gezhao** [comment]
I had the same question above and is it possible Amazon can support this effort too? If it is. pip installable package, then it is easier to use the pydeequ solutions within our own projects. I am interested to help the project. This project is really useful.

**Comment by gezhao** [comment]
I got pydeequ working now with Databricks env. Fairly simple. In my case:
1. I install scala version of package under cluster level setup (install library using maven)
2. I installed pydeequ under the notebook level using pip install <dbfs folder> the dbfs_folder is generated after I used git clone <pydeequ git path...> <dbfs_folder>

**Comment by vr-2020** [comment]
> I got pydeequ working now with Databricks env. Fairly simple. In my case:
> 
> 1. I install scala version of package under cluster level setup (install library using maven)
> 2. I installed pydeequ under the notebook level using pip install  the dbfs_folder is generated after I used git clone  <dbfs_folder>

@gezhao Can you please detail how did you do the step 2 as when I tried to install pip install <com.amazon.deequ:deequ:1.0.5> in the databricks notebook cell I am getting the error.

**Comment by gezhao** [comment]
@vr-2020 I am using these commands to install pydeequ in Databricks. 

%fs mkdirs /aaml/deequ/
%sh git clone https://github.com/margitaii/pydeequ /dbfs/aaml/deequ/
%sh pip install /dbfs/aaml/deequ/

**Comment by margitaii** [comment]
Hi All, pls check out [awslabs/python-deequ](https://github.com/awslabs/python-deequ) this project will continue there...
