### ISSUE TITLE
How to use for AWS Glue (pyspark)

### ISSUE THREAD

**Issue by ankurshri** [margitaii/pydeequ#10]
Hi,

How to use this utility for AWS Glue?
Ask is to check patterns (date format, number format), global file structure and not null columns alone from a csv pattern file provided to us

Thanks

**Comment by margitaii** [comment]
Hi @ankurshri , this project will be continued on [awslabs/python-deequ](https://github.com/awslabs/python-deequ).
Could you pls check out [this tutorial](https://github.com/awslabs/python-deequ/blob/master/tutorials/glue_tutorials/integrate_pydeequ_glue.md)? It might answer your question.
