### ISSUE TITLE
Usage by Multiple Users on Same Machine

### ISSUE THREAD

**Issue by pranavsethi** [margitaii/pydeequ#12]
Hi @margitaii / @dukkona ,

My requirement is using this Library on a Jupyter instance for multiple users to use it . 

Thus , while calling this library , if a spark session is instantiated from one user , the Other user would get this Error :

---------------------------------
/opt/conda/lib/python3.6/site-packages/py4j/java_gateway.py in start_callback_server(self, callback_server_parameters)
   1892 
   1893         try:
-> 1894             self._callback_server.start()
   1895         except Py4JNetworkError:
   1896             # Clean up ourselves before raising the exception.

/opt/conda/lib/python3.6/site-packages/py4j/java_gateway.py in start(self)
   2214                   "server ({0}:{1})".format(self.address, self.port)
   2215             logger.exception(msg)
-> 2216             raise Py4JNetworkError(msg, e)
   2217 
   2218         # Maybe thread needs to be cleanup up?

_**_Py4JNetworkError: An error occurred while trying to start the callback server (127.0.0.1:25334)_**_
------------------------------------------------------------------------

Is there a way we can solve the session like below , Is there a way we can create a pool of Callback servers , or tweak the code in  such way for multiple users to run on the same machine , Your help is much appreciated :  

We currently create this by : 
from pyspark import SparkContext,HiveContext,SparkConf
from pyspark.sql import SparkSession

spark = (SparkSession
              .builder
              .master('local[*]')
              .config('spark.jars.packages',
                      'com.amazon.deequ:deequ:1.0.5')
              .appName('constraint-example-pranav')
              .config("spark.driver.memory", "2g")
              .getOrCreate())

**Comment by margitaii** [comment]
Hi @pranavsethi, could you please check out the [awslabs/python-deequ](https://github.com/awslabs/python-deequ) repo, this project will continue there and your issue might be solved by the guys.
