### ISSUE TITLE
Scala arrays in isContainedIn check

### ISSUE THREAD

**Issue by margitaii** [margitaii/pydeequ#6]
On the Scala side the isContainedIn constrain check requires an Array[String]

`  def isContainedIn(
      column: String,
      allowedValues: Array[String])`

We need a iterable_to_scala_array() function in the `jvm_conversions` module to convert a list of strings in python to Scala array.

**Comment by liunan10** [comment]
Have you fixed this problem? I try to use "sarray = gateway.new_array(gateway.jvm.java.lang.String,2,3)" but encountered an error: 'JavaPackage' object is not callable.

**Comment by liunan10** [comment]
seems fixed it. isContainedIn() can work now.

**Comment by margitaii** [comment]
Hi @liunan10 pls check out [awslabs/python-deequ](https://github.com/awslabs/python-deequ) this project will continue there...
